import Head from "next/head";
import Script from "next/script";

function Header() {
  return (
    <Head>
      <title>Range</title>
      <meta name="description" content="Generated by create next app" />
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no"
      />
      <link rel="icon" href="images/favicon.ico" />
      <link rel="icon" type="image/png" href="images/favicon.png" />
      <link
        rel="shortcut icon"
        type="image/x-icon"
        href="images/favicon.png"
      />
      <link rel="apple-touch-icon" href="images/favicon.png" />
      <link
        rel="shortcut icon"
        type="image/x-icon"
        href="images/favicon.png"
      />
      <meta name="robots" content="index,follow" />

      {/* External script inclusion using Next.js Script component */}
      <Script
        src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"
        strategy="beforeInteractive"
        integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU="
        crossOrigin="anonymous"
      />

      <Script
        src="https://www.googletagmanager.com/gtag/js?id=G-ENW575XKY6"
        strategy="beforeInteractive"
      />
      <Script id="gtag-script">
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-ENW575XKY6');
        `}
      </Script>
    </Head>
  );
}

export default Header;
