"use client";
import Head from "next/head";
import Script from "next/script";
function Header() {
  return (
    <>
      <Head>
        <title>Range</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="images/favicon.ico" />
        <link rel="icon" type="image/png" href="images/favicon.png" />
        <link
          rel="shortcut icon"
          type="image/x-icon"
          href="images/favicon.png"
        />
        <link rel="apple-touch-icon" href="images/favicon.png" />
        <link
          rel="shortcut icon"
          type="image/x-icon"
          href="images/favicon.png"
        />
        <link
          rel="shortcut icon"
          type="image/x-icon"
          href="images/favicon.png"
        />
        <meta name="robots" content="index,follow" />
        <Script
          type="text/javascript"
          src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"
          strategy="beforeInteractive"
          integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU="
          crossOrigin="anonymous"
        />
      </Head>
    </>
  );
}
export default Header;
