import Head from "next/head";
import Script from "next/script";

function Header() {
  return (
    <Head>
      <title>Range</title>
      <meta name="description" content="Generated by create next app" />
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no"
      />
      <link rel="icon" href="images/favicon.ico" />
      <link rel="icon" type="image/png" href="images/favicon.png" />
      <link
        rel="shortcut icon"
        type="image/x-icon"
        href="images/favicon.png"
      />
      <link rel="apple-touch-icon" href="images/favicon.png" />
      <link
        rel="shortcut icon"
        type="image/x-icon"
        href="images/favicon.png"
      />
      <meta name="robots" content="index,follow" />
    </Head>
    
  );
}

export default Header;
